### PR TITLE
[AP-NNNN] Map bit to boolean values

### PR DESCRIPTION
**Pull request by ile-g**
## Problem

pipelinewise-tap-mysql currently maps all non empty bit(1) values as true

## Proposed changes

This change adds an extra mapping for boolean fields so that values from MySQL bit columns are mapped correctly : b'0'-> False.
Issue reference: https://github.com/transferwise/pipelinewise-tap-mysql/issues/37

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Description above provides context of the change
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Unit tests for changes (not needed for documentation changes)
- [ ] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [x] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [ ] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [x] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Comment by Samira-El** [comment]
Hey there, thank you for this fix!

As this tap is used in [Pipelinewise](https://github.com/transferwise/pipelinewise) which has two ways of doing replication: FastSync and Singer, we need the two to be in sync at all time, thus, FastSync needs to behave the same way as this tap in terms of handling `b'0'`.

Do you think you can create a PR in Pipelinewise that introduces this same fix?

**Comment by ile-g** [comment]
Hey, thank you for the feedback!

I went over the FastSyncTapMysql code and there is no need for `b'0'` handling because of the conversion from `bit` to `unsigned` when selecting the data in [line 213](https://github.com/transferwise/pipelinewise/blob/87cfc5013b5ae20279197f808cec9cbaf23b6819/pipelinewise/fastsync/commons/tap_mysql.py#L213). With this conversion, the returned values from `bit` columns are integer values.

**Comment by Samira-El** [comment]
Thanks for checking!

There is another place that requires the same change, it's for the binlog replication [here](https://github.com/transferwise/pipelinewise-tap-mysql/blob/60f67df286da9c4b00c80d22baa5dfaa4f3d8426/tap_mysql/sync_strategies/binlog.py#L176)

**Comment by ile-g** [comment]
Checked the binlog replication: BIT columns are extracted correctly in this type of sync. 
They are converted to int and evaluated [here](https://github.com/transferwise/pipelinewise-tap-mysql/blob/60f67df286da9c4b00c80d22baa5dfaa4f3d8426/tap_mysql/sync_strategies/binlog.py#L178). Hope this covers it!

**Comment by Samira-El** [comment]
Thanks for checking, do you mind creating few regression/unit tests to cover this change?

**Comment by ile-g** [comment]
Hi @Samira-El, I added a basic test that checks the bit to boolean mapping logic. Let me know if more is needed.

**Review by koszti — APPROVED** [review]

**Pull request merged**
